version: 2
jobs:
  build:
    
    working_directory: ~/darkflame123

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      
      - run: mvn dependency:go-offline
      
      
      - run: mvn clean package

      - store_artifacts:
          path: target/Nukkit-PM1E.jar
